INSERT INTO DEPT
VALUES(10, 'TEST', 'SEOUL');

--DBeaver에서는 수행 안됨
DESC USER_CONSTRAINTS;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME 
FROM USER_CONSTRAINTS; 

SELECT * 
FROM USER_CONS_COLUMNS;

CREATE TABLE EMP01( 
	EMPNO NUMBER(4), 
	ENAME VARCHAR2(10), 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2));

INSERT INTO EMP01
VALUES(NULL, NULL, 'SALESMAN', 30);

SELECT * FROM EMP01;

DESC EMP01;

CREATE TABLE EMP02( 
	EMPNO NUMBER(4) NOT NULL, 
	ENAME VARCHAR2(10) NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2)); 

INSERT INTO EMP02
VALUES(NULL, NULL, 'SALESMAN', 10);

DESC EMP02;

CREATE TABLE EMP03( 
	EMPNO NUMBER(4) UNIQUE,
	ENAME VARCHAR2(10) NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2)); 

INSERT INTO EMP03
VALUES(7499, 'ALLEN', 'SALESMAN', 30);

INSERT INTO EMP03
VALUES(7499, 'JONES', 'MANAGER', 20);

INSERT INTO EMP03
VALUES(NULL, 'JONES', 'MANAGER', 20);

INSERT INTO EMP03
VALUES(NULL, 'JONES', 'SALESMAN', 10);

CREATE TABLE EMP04( 
	EMPNO NUMBER(4) CONSTRAINT EMP04_EMPNO_UK UNIQUE,
	ENAME VARCHAR2(10) CONSTRAINT EMP04_ENAME_NN NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2));

SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP04');

INSERT INTO EMP03
VALUES(NULL, 'JONES', 'MANAGER', 20);

INSERT INTO EMP03
VALUES(NULL, 'JONES', 'SALESMAN', 10);

SELECT *
FROM EMP03;

CREATE TABLE EMP05( 
	EMPNO NUMBER(4) CONSTRAINT EMP05_EMPNO_PK PRIMARY KEY ,
	ENAME VARCHAR2(10) CONSTRAINT EMP05_ENAME_NN NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2)
); 

INSERT INTO EMP05
VALUES(7499, 'ALLEN', 'SALESMAN', 30);

INSERT INTO EMP05
VALUES(7499, 'JONES', 'MANAGER', 20);

INSERT INTO EMP05
VALUES(NULL, 'JONES', 'MANAGER', 20);

SELECT TABLE_NAME, CONSTRAINT_TYPE, 
CONSTRAINT_NAME, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPT', 'EMP');

CREATE TABLE EMP06( 
	EMPNO NUMBER(4) CONSTRAINT EMP06_EMPNO_PK PRIMARY KEY ,
	ENAME VARCHAR2(10) CONSTRAINT EMP06_ENAME_NN NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2) CONSTRAINT EMP06_DEPTNO_FK REFERENCES DEPT(DEPTNO)
); 

INSERT INTO EMP06
VALUES(7566, 'JONES', 'MANAGER', 50);

CREATE TABLE EMP07( 
	EMPNO NUMBER(4) CONSTRAINT EMP07_EMPNO_PK PRIMARY KEY ,
	ENAME VARCHAR2(10) CONSTRAINT EMP07_ENAME_NN NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(2)CONSTRAINT EMP07_DEPTNO_FK REFERENCES DEPT(DEPTNO)ON DELETE CASCADE
); 

CREATE TABLE EMP08( 
	EMPNO NUMBER(4) CONSTRAINT EMP08_EMPNO_PK PRIMARY KEY ,
	ENAME VARCHAR2(10) CONSTRAINT EMP08_ENAME_NN NOT NULL, 
	SAL NUMBER(7, 2)CONSTRAINT EMP08_SAL_CK CHECK(SAL BETWEEN 500 AND 5000),
	GENDER VARCHAR2(1) CONSTRAINT EMP08_GENDER_CK CHECK (GENDER IN('M', 'F'))
);

CREATE TABLE DEPT01(
	DEPTNO NUMBER(2) PRIMARY KEY,
	DNAME VARCHAR2(14),
	LOC VARCHAR2(13) DEFAULT 'SEOUL'
);

INSERT INTO DEPT01(DEPTNO, DNAME)
VALUES(10, 'ACCOUNTING');

SELECT *
FROM DEPT01;

CREATE TABLE EMP11( 
	EMPNO NUMBER(4) PRIMARY KEY,
	ENAME VARCHAR2(10) NOT NULL, 
	JOB VARCHAR2(9) UNIQUE,
	DEPTNO NUMBER(4) REFERENCES DEPT(DEPTNO)); 

CREATE TABLE EMP12( 
	EMPNO NUMBER(4),
	ENAME VARCHAR2(10) NOT NULL, 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(4),
	PRIMARY KEY(EMPNO),
	UNIQUE(JOB),
	FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)
);

CREATE TABLE EMP13( 
	EMPNO NUMBER(4) CONSTRAINT EMP13_ENAME_NN NOT NULL,
	ENAME VARCHAR2(10), 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(4),
	CONSTRAINT EMP13_EMPNO_PK PRIMARY KEY(EMPNO),
	CONSTRAINT EMP13_JOB_UK UNIQUE(JOB),
	CONSTRAINT EMP13_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)
); 

CREATE TABLE MEMBER01( 
	NAME VARCHAR2(10),
	ADDRESS VARCHAR2(30),
	HPHONE VARCHAR2(16),
	CONSTRAINT MEMBER01_COMBO_PK PRIMARY KEY(NAME, HPHONE)
);

CREATE TABLE EMP21( 
	EMPNO NUMBER(4), 
	ENAME VARCHAR2(10), 
	JOB VARCHAR2(9),
	DEPTNO NUMBER(4)); 

ALTER TABLE EMP21
ADD CONSTRAINT EMP21_EMPNO_PK PRIMARY KEY(EMPNO);

ALTER TABLE EMP21
ADD CONSTRAINT EMP21_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);

ALTER TABLE EMP21
MODIFY ENAME CONSTRAINT EMP21_ENAME_NN NOT NULL;

ALTER TABLE EMP21
DROP CONSTRAINT EMP21_EMPNO_PK;

ALTER TABLE EMP21
DROP CONSTRAINT EMP21_ENAME_NN;

CREATE TABLE DEPT31(
	DEPTNO NUMBER(2) CONSTRAINT DEPT01_DEPTNO_PK PRIMARY KEY,
	DNAME VARCHAR2(14),
	LOC VARCHAR2(13)
);

CREATE TABLE EMP31( 
	EMPNO NUMBER(4) CONSTRAINT EMP31_EMPNO_PK PRIMARY KEY ,
	ENAME VARCHAR2(10) CONSTRAINT EMP31_ENAME_NN NOT NULL, 
	JOB VARCHAR2(9), 
	DEPTNO NUMBER(4) CONSTRAINT EMP31_DEPTNO_FK REFERENCES DEPT31(DEPTNO)
); 

INSERT INTO DEPT31 VALUES(10, 'ACCOUNT', 'SEOUL');
INSERT INTO DEPT31 VALUES(20, 'SALES', 'MOKPO');

INSERT INTO EMP31 VALUES(7499, 'ALLEN', 'SALESMAN', 10);
INSERT INTO EMP31 VALUES(7369, 'SMITH', 'CLERK', 20);

DELETE FROM DEPT31 WHERE DEPTNO=10;

ALTER TABLE EMP31
DISABLE CONSTRAINT EMP31_DEPTNO_FK;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, 
TABLE_NAME, R_CONSTRAINT_NAME, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP31';

DELETE FROM DEPT31
WHERE DEPTNO=10;

ALTER TABLE EMP31
ENABLE CONSTRAINT EMP31_DEPTNO_FK;

INSERT INTO DEPT31
VALUES(10, 'ACCOUNTING', 'NEW YORK');

SELECT * FROM DEPT31;

ALTER TABLE EMP31
ENABLE CONSTRAINT EMP31_DEPTNO_FK;

ALTER TABLE DEPT31
DISABLE PRIMARY KEY;

ALTER TABLE DEPT31
DISABLE PRIMARY KEY CASCADE;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, 
TABLE_NAME, R_CONSTRAINT_NAME, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('DEPT31', 'EMP31');
